=== OMRYZUTA/evolution/javaFXApplication/src/resources/ex2/ETT-V2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ETT-TimeTable">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ETT-Teachers"/>
                <xs:element ref="ETT-Subjects"/>
                <xs:element ref="ETT-Classes"/>
                <xs:element ref="ETT-Rules"/>
            </xs:sequence>
            <xs:attribute name="hours" type="xs:int" use="required"/>
            <xs:attribute name="days" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Teaching">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ETT-Teaches" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Teaches">
        <xs:complexType>
            <xs:attribute name="subject-id" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Teachers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ETT-Teacher" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Teacher">
        <xs:complexType>
            <xs:all>
                <xs:element ref="ETT-Name"/>
                <xs:element ref="ETT-Teaching"/>
            </xs:all>
            <xs:attribute name="id" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Subjects">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ETT-Subject" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Subject">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="id" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Study">
        <xs:complexType>
            <xs:attribute name="subject-id" type="xs:int" use="required"/>
            <xs:attribute name="hours" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Selection">
        <xs:complexType>
            <xs:all>
                <xs:element name="ETT-Elitism" type="xs:int" minOccurs="0"/>
            </xs:all>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Truncation"/>
                        <xs:enumeration value="RouletteWheel"/>
                        <xs:enumeration value="Tournament"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="configuration" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Rules">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ETT-Rule" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="hard-rules-weight" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-RuleId">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="TeacherIsHuman"/>
                <xs:enumeration value="Singularity"/>
                <xs:enumeration value="Knowledgeable"/>
                <xs:enumeration value="DayOffTeacher"/>
                <xs:enumeration value="Sequentiality"/>
                <xs:enumeration value="Satisfactory"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="ETT-Rule">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ETT-RuleId"/>
                <xs:element ref="ETT-Configuration" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Hard"/>
                        <xs:enumeration value="Soft"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Requirements">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ETT-Study" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Name" type="xs:string"/>
    <xs:element name="ETT-Mutations">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ETT-Mutation" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Mutation">
        <xs:complexType>
            <xs:attribute name="probability" type="xs:double" use="required"/>
            <xs:attribute name="name" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Flipping"/>
                        <xs:enumeration value="Sizer"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="configuration" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-InitialPopulation">
        <xs:complexType>
            <xs:attribute name="size" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-EvolutionEngine">
        <xs:complexType>
            <xs:all>
                <xs:element ref="ETT-InitialPopulation"/>
                <xs:element ref="ETT-Selection"/>
                <xs:element ref="ETT-Crossover"/>
                <xs:element ref="ETT-Mutations"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Descriptor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ETT-TimeTable"/>
                <xs:element ref="ETT-EvolutionEngine"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Configuration" type="xs:string"/>
    <xs:element name="ETT-Crossover">
        <xs:complexType>
            <xs:attribute name="configuration" type="xs:string"/>
            <xs:attribute name="name" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="AspectOriented"/>
                        <xs:enumeration value="DayTimeOriented"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="cutting-points" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Classes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ETT-Class" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ETT-Class">
        <xs:complexType>
            <xs:all>
                <xs:element ref="ETT-Name"/>
                <xs:element ref="ETT-Requirements"/>
            </xs:all>
            <xs:attribute name="id" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== OMRYZUTA/evolution/javaFXApplication/src/resources/EX2-smallForApect(oldSelectionAndRules).xml
<?xml version="1.0" encoding="UTF-8"?>
<ETT-Descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ETT-V2.xsd">
    <ETT-TimeTable days="4" hours="5">
        <ETT-Teachers>
            <ETT-Teacher id="1">
                <ETT-Name>Mika Rali</ETT-Name>
                <ETT-Teaching>
                    <ETT-Teaches subject-id="1"/>
                    <ETT-Teaches subject-id="2"/>
                </ETT-Teaching>
            </ETT-Teacher>
            <ETT-Teacher id="3">
                <ETT-Name>Maya Tzalach</ETT-Name>
                <ETT-Teaching>
                    <ETT-Teaches subject-id="3"/>
                </ETT-Teaching>
            </ETT-Teacher>
            <ETT-Teacher id="2">
                <ETT-Name>Mia Charon</ETT-Name>
                <ETT-Teaching>
                    <ETT-Teaches subject-id="2"/>
                    <ETT-Teaches subject-id="3"/>
                </ETT-Teaching>
            </ETT-Teacher>
            <ETT-Teacher id="4">
                <ETT-Name>Mati Knili</ETT-Name>
                <ETT-Teaching>
                    <ETT-Teaches subject-id="2"/>
                    <ETT-Teaches subject-id="4"/>
                </ETT-Teaching>
            </ETT-Teacher>
        </ETT-Teachers>
        <ETT-Subjects>
            <ETT-Subject id="1" name="Sifrut"/>
            <ETT-Subject id="3" name="Tanach"/>
            <ETT-Subject id="4" name="English"/>
            <ETT-Subject id="2" name="Math"/>
        </ETT-Subjects>
        <ETT-Classes>
            <ETT-Class id="1">
                <ETT-Name>Standart</ETT-Name>
                <ETT-Requirements>
                    <ETT-Study subject-id="1" hours="3"/>
                    <ETT-Study subject-id="2" hours="4"/>
                    <ETT-Study subject-id="3" hours="2"/>
                </ETT-Requirements>
            </ETT-Class>
            <ETT-Class id="2">
                <ETT-Name>Nerds</ETT-Name>
                <ETT-Requirements>
                    <ETT-Study subject-id="2" hours="6"/>
                    <ETT-Study subject-id="4" hours="6"/>
                </ETT-Requirements>
            </ETT-Class>
            <ETT-Class id="3">
                <ETT-Name>Tikshoret</ETT-Name>
                <ETT-Requirements>
                    <ETT-Study subject-id="4" hours="2"/>
                    <ETT-Study subject-id="1" hours="4"/>
                    <ETT-Study subject-id="3" hours="6"/>
                    <ETT-Study subject-id="2" hours="4"/>
                </ETT-Requirements>
            </ETT-Class>
            <ETT-Class id="4">
                <ETT-Name>Biologit</ETT-Name>
                <ETT-Requirements>
                    <ETT-Study subject-id="4" hours="2"/>
                    <ETT-Study subject-id="2" hours="4"/>
                </ETT-Requirements>
            </ETT-Class>
        </ETT-Classes>
        <ETT-Rules hard-rules-weight="70">
            <ETT-Rule type="Hard">
                <ETT-RuleId>TeacherIsHuman</ETT-RuleId>
            </ETT-Rule>
            <ETT-Rule type="Hard">
                <ETT-RuleId>Singularity</ETT-RuleId>
            </ETT-Rule>
            <ETT-Rule type="Hard">
                <ETT-RuleId>Knowledgeable</ETT-RuleId>
            </ETT-Rule>
            <ETT-Rule type="Hard">
                <ETT-RuleId>Satisfactory</ETT-RuleId>
            </ETT-Rule>
        </ETT-Rules>
    </ETT-TimeTable>
    <ETT-EvolutionEngine>
        <ETT-InitialPopulation size="100"/>
        <ETT-Selection type="Truncation" configuration="TopPercent=10">
            <ETT-Elitism>5</ETT-Elitism>
        </ETT-Selection>
        <ETT-Crossover name="AspectOriented" cutting-points="1" configuration="Orientation=CLASS"/>
        <ETT-Mutations>
            <ETT-Mutation name="Flipping" probability="0.2" configuration="MaxTupples=3,Component=D"/>
            <ETT-Mutation name="Sizer" probability="0.3" configuration="TotalTupples=7"/>
        </ETT-Mutations>
    </ETT-EvolutionEngine>
</ETT-Descriptor>

=== OMRYZUTA/evolution/javaFXApplication/src/resources/ex2/EX2-DayOffTeacherOnly.xml
<?xml version="1.0" encoding="UTF-8"?>
<ETT-Descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ETT-V2.xsd">
    <ETT-TimeTable days="6" hours="8">
        <ETT-Teachers>
            <ETT-Teacher id="1">
                <ETT-Name>Alma Nedaber</ETT-Name>
                <ETT-Teaching>
                    <ETT-Teaches subject-id="1"/>
                    <ETT-Teaches subject-id="2"/>
                </ETT-Teaching>
            </ETT-Teacher>
            <ETT-Teacher id="3">
                <ETT-Name>Miki Peli</ETT-Name>
                <ETT-Teaching>
                    <ETT-Teaches subject-id="3"/>
                </ETT-Teaching>
            </ETT-Teacher>
            <ETT-Teacher id="2">
                <ETT-Name>Mali Vela</ETT-Name>
                <ETT-Teaching>
                    <ETT-Teaches subject-id="4"/>
                    <ETT-Teaches subject-id="5"/>
                </ETT-Teaching>
            </ETT-Teacher>
            <ETT-Teacher id="4">
                <ETT-Name>Lola Tet</ETT-Name>
                <ETT-Teaching>
                    <ETT-Teaches subject-id="6"/>
                    <ETT-Teaches subject-id="3"/>
                    <ETT-Teaches subject-id="7"/>
                </ETT-Teaching>
            </ETT-Teacher>
            <ETT-Teacher id="6">
                <ETT-Name>Tiki Pur</ETT-Name>
                <ETT-Teaching>
                    <ETT-Teaches subject-id="5"/>
                    <ETT-Teaches subject-id="1"/>
                    <ETT-Teaches subject-id="7"/>
                </ETT-Teaching>
            </ETT-Teacher>
            <ETT-Teacher id="5">
                <ETT-Name>Hugo Zer</ETT-Name>
                <ETT-Teaching>
                    <ETT-Teaches subject-id="1"/>
                    <ETT-Teaches subject-id="2"/>
                    <ETT-Teaches subject-id="3"/>
                    <ETT-Teaches subject-id="4"/>
                    <ETT-Teaches subject-id="5"/>
                    <ETT-Teaches subject-id="6"/>
                </ETT-Teaching>
            </ETT-Teacher>
        </ETT-Teachers>
        <ETT-Subjects>
            <ETT-Subject id="1" name="Sifrut"/>
            <ETT-Subject id="3" name="Tanach"/>
            <ETT-Subject id="4" name="English"/>
            <ETT-Subject id="5" name="Math"/>
            <ETT-Subject id="2" name="Physics"/>
            <ETT-Subject id="6" name="Tongue"/>
            <ETT-Subject id="7" name="Biology"/>
        </ETT-Subjects>
        <ETT-Classes>
            <ETT-Class id="1">
                <ETT-Name>Standart</ETT-Name>
                <ETT-Requirements>
                    <ETT-Study subject-id="1" hours="10"/>
                    <ETT-Study subject-id="3" hours="12"/>
                    <ETT-Study subject-id="6" hours="4"/>
                    <ETT-Study subject-id="5" hours="4"/>
                    <ETT-Study subject-id="2" hours="2"/>
                </ETT-Requirements>
            </ETT-Class>
            <ETT-Class id="2">
                <ETT-Name>Nerds</ETT-Name>
                <ETT-Requirements>
                    <ETT-Study subject-id="1" hours="2"/>
                    <ETT-Study subject-id="3" hours="2"/>
                    <ETT-Study subject-id="6" hours="4"/>
                    <ETT-Study subject-id="2" hours="12"/>
                    <ETT-Study subject-id="4" hours="12"/>
                    <ETT-Study subject-id="5" hours="12"/>
                </ETT-Requirements>
            </ETT-Class>
            <ETT-Class id="3">
                <ETT-Name>Tikshoret</ETT-Name>
                <ETT-Requirements>
                    <ETT-Study subject-id="1" hours="4"/>
                    <ETT-Study subject-id="3" hours="4"/>
                    <ETT-Study subject-id="6" hours="6"/>
                    <ETT-Study subject-id="2" hours="4"/>
                    <ETT-Study subject-id="4" hours="4"/>
                </ETT-Requirements>
            </ETT-Class>
            <ETT-Class id="4">
                <ETT-Name>Biologit</ETT-Name>
                <ETT-Requirements>
                    <ETT-Study subject-id="1" hours="2"/>
                    <ETT-Study subject-id="3" hours="2"/>
                    <ETT-Study subject-id="6" hours="4"/>
                    <ETT-Study subject-id="2" hours="6"/>
                    <ETT-Study subject-id="4" hours="6"/>
                    <ETT-Study subject-id="5" hours="6"/>
                    <ETT-Study subject-id="7" hours="12"/>
                </ETT-Requirements>
            </ETT-Class>
            <ETT-Class id="5">
                <ETT-Name>Science</ETT-Name>
                <ETT-Requirements>
                    <ETT-Study subject-id="1" hours="3"/>
                    <ETT-Study subject-id="3" hours="3"/>
                    <ETT-Study subject-id="6" hours="3"/>
                    <ETT-Study subject-id="2" hours="3"/>
                    <ETT-Study subject-id="4" hours="3"/>
                    <ETT-Study subject-id="5" hours="3"/>
                    <ETT-Study subject-id="7" hours="3"/>
                </ETT-Requirements>
            </ETT-Class>
        </ETT-Classes>
        <ETT-Rules hard-rules-weight="100">
            <ETT-Rule type="Hard">
                <ETT-RuleId>DayOffTeacher</ETT-RuleId>
            </ETT-Rule>
        </ETT-Rules>
    </ETT-TimeTable>
    <ETT-EvolutionEngine>
        <ETT-InitialPopulation size="150"/>
        <ETT-Selection type="Truncation" configuration="TopPercent=20"/>
        <ETT-Crossover name="DayTimeOriented" cutting-points="4"/>
        <ETT-Mutations>
            <ETT-Mutation name="Flipping" probability="0.4" configuration="MaxTupples=3,Component=D"/>
        </ETT-Mutations>
    </ETT-EvolutionEngine>
</ETT-Descriptor>
